services:
  - type: web
    name: mp-notifier
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: SECRET_KEY
        value: "cambia-esto-por-una-clave-larga-y-segura"
